name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install pthon
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt install python3.8
      - name: print python version
        run: python --version
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install packages
        run: pipenv install --dev
      - name: Run cli
        run: pipenv run abe_importer --help
