name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Run a multi-line script
        run: pipenv install --dev
      - name: Run cli
        run: pipenv run abe_importer --help
